GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "John@gmail.com",
    "gender": "Male"
}


###
PATCH  http://localhost:5000/users/2
Content-Type: application/json

{
    "name": "Blaze",
    "email": "Blaze@gmail.com",
    "gender": "Male"
}
###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "Blaze Rod",
    "email": "Blaze@gmail.com",
    "gender": "Male"
}
###
DELETE  http://localhost:5000/users/1
